[package]
name = "glsp-mcp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# MCP Framework dependencies - using git repository directly
# Note: These crates are not published to crates.io yet, so we reference the git repo
mcp-server = { package = "mcp-server", git = "https://github.com/avrabe/mcp-loxone.git" }
mcp-protocol = { package = "mcp-protocol", git = "https://github.com/avrabe/mcp-loxone.git" }
mcp-transport = { package = "mcp-transport", git = "https://github.com/avrabe/mcp-loxone.git" }
mcp-auth = { package = "mcp-auth", git = "https://github.com/avrabe/mcp-loxone.git" }
mcp-security = { package = "mcp-security", git = "https://github.com/avrabe/mcp-loxone.git" }
mcp-monitoring = { package = "mcp-monitoring", git = "https://github.com/avrabe/mcp-loxone.git" }

# Workspace dependencies
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
futures = { workspace = true }

# HTTP and server dependencies (still needed for custom code)
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }

# WASM processing
wasm-tools = { workspace = true }
wasmparser = { workspace = true }
wit-component = { workspace = true }
wit-parser = { workspace = true }
chrono = { workspace = true }

# Filesystem watching
notify = "6.1"

# SSE support
axum-extra = { version = "0.9", features = ["typed-header"] }
async-stream = "0.3"
tokio-stream = "0.1"

# CLI argument parsing
clap = { version = "4.0", features = ["derive"] }

[lib]
name = "glsp_mcp_server"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/main.rs"