[package]
name = "glsp-mcp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
thiserror = "1.0"
chrono = { version = "0.4", features = ["serde"] }
wasm-tools = "1.0"
wasmparser = "0.118"

[lib]
name = "glsp_mcp_server"
path = "src/lib.rs"

[[bin]]
name = "server"
path = "src/main.rs"