[package]
name = "adas-video_decoder"
version = "0.1.0"
edition = "2021"
description = "Video decoder for ADAS automotive video processing"
license = "Apache-2.0"


[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.33"
mp4parse = "0.17"
lru = "0.12"

# Configuration for building WASM components
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"