[package]
name = "adas-camera_surround_ecu"
version = "0.1.0"
edition = "2021"
description = "360° surround-view camera system"
license = "Apache-2.0"


[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true }

# Configuration for building WASM components
# Profile configuration inherited from workspace
