[package]
name = "showcase-pipeline"
version = "0.1.0"
edition = "2021"
description = "Production-grade data pipeline for automotive ADAS showcase"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
# No build dependencies for showcase version

# Showcase profile for demo optimization
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true