[package]
name = "adas-camera-front-ecu"
version = "0.1.0"
edition = "2021"
description = "Front-facing camera ECU with AI vision processing"
license = "Apache-2.0"


[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true }
component-metadata = { workspace = true }
serde_json = { workspace = true }

[build-dependencies]
component-metadata = { path = "../../../component-metadata", features = ["build"] }

# Profile configuration inherited from workspace
