[package]
name = "adas-camera-front-ecu"
version = "0.1.0"
edition = "2021"
description = "Front-facing camera ECU with AI vision processing"
license = "Apache-2.0"


[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { git = "https://github.com/avrabe/wit-bindgen.git", branch = "feat/developer-experience-enhancements", package = "wit-bindgen" }
component-metadata = { path = "../../../component-metadata" }
serde_json = "1.0"

[build-dependencies]
component-metadata = { path = "../../../component-metadata", features = ["build"] }

# Configuration for building WASM components
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"