[package]
name = "adas-gfx-visualizer"
version = "0.1.0"
edition = "2021"
description = "ADAS Graphics Visualizer using wasi-gfx for real-time video and detection overlay"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "adas:graphics-visualizer"

[dependencies]
wit-bindgen = { workspace = true }
# Note: wasi-gfx bindings would be added when available
# wasi-gfx = "0.1.0"  # Future dependency
bytemuck = { workspace = true }
image = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# Configuration for building WASM components
# Profile configuration inherited from workspace
