[component]
name = "adas-perception"
version = "0.1.0"
description = "Perception component for object detection, tracking, and scene understanding in ADAS systems"
author = "ADAS Development Team"
license = "Apache-2.0"
created = "2025-06-26"

[interfaces]
exports = ["adas:perception/perception"]
imports = ["adas:sensor-fusion/types"]

[dependencies]
external = [
    "adas:sensor-fusion@0.1.0"
]

[hardware_requirements]
min_cpu_cores = 4
min_memory_mb = 2048
min_storage_mb = 500
requires_gpu = true
gpu_memory_mb = 4096
supported_architectures = ["x86_64", "aarch64"]

[real_time_constraints]
max_processing_latency_ms = 100
update_frequency_hz = 10
priority_level = "high"
deadline_type = "soft"

[safety_certification]
iso26262_asil = "C"  # Automotive Safety Integrity Level C
functional_safety_tested = true
fail_safe_behavior = "maintain_last_detection"
redundancy_required = false

[performance_characteristics]
object_detection_accuracy = 0.95  # mAP at IoU 0.5
tracking_accuracy = 0.90          # MOTA metric
false_positive_rate = 0.02
false_negative_rate = 0.05
processing_latency_ms = 80
memory_usage_mb = 1024
gpu_usage_percent = 70

[ai_models]
object_detection_models = [
    "yolov8",
    "faster_rcnn", 
    "ssd_mobilenet",
    "efficientdet"
]

tracking_algorithms = [
    "deep_sort",
    "byte_track",
    "kalman_tracker",
    "particle_filter"
]

semantic_segmentation_models = [
    "deeplabv3",
    "unet",
    "pspnet",
    "hrnet"
]

supported_frameworks = [
    "pytorch",
    "tensorflow",
    "onnx",
    "tensorrt"
]

[sensor_support]
camera_types = [
    "rgb",
    "stereo",
    "fisheye",
    "thermal"
]

camera_resolutions = [
    "640x480",
    "1280x720", 
    "1920x1080",
    "2560x1440"
]

lidar_types = [
    "mechanical_spinning",
    "solid_state", 
    "flash_lidar"
]

radar_types = [
    "short_range",
    "medium_range",
    "long_range"
]

[detection_capabilities]
object_classes = [
    "car",
    "truck", 
    "bus",
    "motorcycle",
    "bicycle",
    "pedestrian",
    "traffic_sign",
    "traffic_light",
    "lane_marking",
    "road_barrier"
]

detection_range_meters = 200
min_object_size_pixels = 16
max_objects_per_frame = 100

[scene_understanding]
lane_detection = true
drivable_area_detection = true
traffic_sign_recognition = true
traffic_light_detection = true
weather_estimation = true
visibility_estimation = true

occupancy_grid_resolution_meters = 0.1
occupancy_grid_size_meters = 100

[calibration]
supports_auto_calibration = true
calibration_accuracy_pixels = 0.5
extrinsic_calibration_methods = [
    "checkerboard",
    "april_tags",
    "automatic"
]

temporal_calibration = true
spatial_calibration = true

[testing]
unit_tests_coverage = 92
integration_tests = true
hardware_in_loop_tested = true

simulation_environments = [
    "carla",
    "airsim",
    "lgsvl",
    "prescan"
]

benchmark_datasets = [
    "coco",
    "kitti",
    "nuscenes",
    "cityscapes",
    "bdd100k"
]

evaluation_metrics = [
    "mAP",      # mean Average Precision
    "MOTA",     # Multiple Object Tracking Accuracy  
    "IOU",      # Intersection over Union
    "FPS"       # Frames Per Second
]

[documentation]
api_documentation = "docs/perception_api.md"
model_documentation = "docs/perception_models.md"
calibration_guide = "docs/perception_calibration.md"
performance_tuning = "docs/perception_tuning.md"