[package]
name = "adas-sensor-fusion-ecu"
version = "0.1.0"
edition = "2021"
description = "Multi-modal sensor fusion ECU with Kalman filtering"
license = "Apache-2.0"


[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true }

# Configuration for building WASM components
# Profile configuration inherited from workspace
