[package]
name = "adas-adas_domain_controller"
version = "0.1.0"
edition = "2021"
description = "Central ADAS coordinator"
license = "Apache-2.0"


[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true }

# Configuration for building WASM components
# Profile configuration inherited from workspace
